security:
  basic:
   enabled: false 

management:
  security:
     enabled: false

logging:
  level:
   io:
    pivotal: DEBUG

greeting:
  displayForture: false

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
